spring:
  datasource:
    url: jdbc:mysql://xxxxxxxxx:3306/test_db
    username: xxxxxxxxx
    password: xxxxxxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  servlet:
    session:
      timeout: 10
  tomcat:
    uri-encoding: UTF-8
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:com.example.backend.dao/**/*.xml
logging:
  level:
    com:
      example:
        backend:
          dao: debug